MLP_window: 15
data_path: ./train_test_split_storage/
dropout: 0.15
hidden_size: 500
label_scale_position: 90
label_scale_velocity: 400
learning_rate: 0.0005
manual_test_set: true
model_path: ./best_model.pt
model_prediction: both
model_type: LSTM
num_epochs: 4
num_features: 142
num_layers: 3
plot_path: ./
resume_from_checkpoint: false
sample: front
test_batch_size: 1
test_only: false
train_batch_size: 4
train_frac: 0.8
use_wandb: true
wandb_name: Pivot-Training
wandb_project: Grav_Pivot
wandb_run_notes: ''
weight_decay: 1.0e-06
